"""empty message

Revision ID: dfd75cea0a43
Revises: 
Create Date: 2022-03-26 14:50:20.814492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd75cea0a43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dishes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'category_id')
    # ### end Alembic commands ###
